<?php

/**
 * JobeetJobTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobeetJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetJob');
    }

    public function getActiveJobs(Doctrine_Query $query = null)
    {
        if (!isset($query)) {
            $query = Doctrine_Query::create()
                ->from('JobeetJob j');
        }

        $date  = date('Y-m-d H:i:s');
        $query->andWhere('j.expires_at > ?', $date)
            ->addOrderBy('j.expires_at DESC');

        return $query->execute();
    }

    public function retrieveActiveJob(Doctrine_Query $query)
    {
        $date  = date('Y-m-d H:i:s');
        $query->andWhere('a.expires_at > ?', $date);

        return $query->fetchOne();
    }
}