<?php

/**
 * JobeetAffiliateTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JobeetAffiliateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JobeetAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JobeetAffiliate');
    }

    public function countToBeActivated()
    {
        $query = $this->createQuery('a')
            ->where('a.is_active = ?', 0);

        return $query->count();
    }

    public function activateAffiliates(array $ids)
    {
        return $this->_activateOrDeactivateAffiliates($ids, true);
    }

    public function deactivateAffiliates(array $ids)
    {
        return $this->_activateOrDeactivateAffiliates($ids, false);
    }

    private function _activateOrDeactivateAffiliates(array $ids, $activate)
    {
        $query = Doctrine_Query::create()
          ->from('JobeetAffiliate a')
          ->whereIn('a.id', $ids);

        $conn = sfContext::getInstance()->getDatabaseManager()->getDatabase('doctrine')->getDoctrineConnection();

        try {
            $conn->beginTransaction();

            $affiliates = $query->execute();

            foreach ($affiliates as $affiliate) {
                if ($activate) {
                    $affiliate->activate();
                } else {
                    $affiliate->deactivate();
                }
            }

            // Commit the transaction when done
            $conn->commit();

            return true;
        } catch (Doctrine_Exception $e) {
            // Rollback if transaction fail
            $conn->rollback();
        }

        return false;
    }
}