<?php

/**
 * JobeetCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class JobeetCategory extends BaseJobeetCategory
{
    public function getActiveJobs($max = null)
    {
        $table = Doctrine_Core::getTable('JobeetJob');
        /* @var $table JobeetJobTable */

        $query = $this->getActiveJobsQuery();

        if (isset($max) && is_int($max) && $max) {
            $query->limit($max);
        }

        return $query->execute();
    }

    public function countActiveJobs()
    {
        return $this->getActiveJobsQuery()->count();
    }

    public function getActiveJobsQuery()
    {
        $table = Doctrine_Core::getTable('JobeetJob');
        /* @var $table JobeetJobTable */

        $query = Doctrine_Query::create()
            ->from('JobeetJob j')
            ->where('j.category_id = ?', $this->getId());

        return $table->addActiveJobsQuery($query);
    }
}