all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=localhost;dbname=jobeet;port=5432'
      username: jobeet
      password: jobeet
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'pgsql:host=localhost;dbname=jobeet_test;port=5432'
      username: jobeet
      password: jobeet
